services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: swift
      POSTGRES_USER: swift
      POSTGRES_PASSWORD: swift
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "swift"]
      interval: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGHOST: db
volumes:
  db-data:
